create_env:
	conda env create --prefix ./{{cookiecutter.project_name}}_env -f {{cookiecutter.project_name}}_env.yml

activate_env:
	conda activate ./{{cookiecutter.project_name}}_env

deactivate_env:
	conda deactivate
	
deploy_app:
	echo

test:
